Working on rectifying AWS deploy example.
shakenfist/deploy pull request #17
Opened 2020-07-10 02:22 UTC by mikalstill

2020-07-10 03:38 UTC, mandoonandy requested changes
I'm hoping my inline comment survives. If not, line allow_ssh is repeated and needs to change to allow_api.

Should we also change the last step install step in the README to utilise our new fancy deploy script?

2020-07-10 03:38 UTC, mandoonandy commented on ansible/terraform/aws/setup.tf
> +    aws_security_group.sf_allow_ssh.id,
Trying to comment about line 118 aws/setup.tf - is there no reference included?

This line I think should by allow_api. Same applies for sf_2 and 3.

2020-07-10 23:10 UTC, mikalstill commented
@mandoonandy I think being forced to rearrange the number of security groups by AWS has accidentally addressed your concern? This works now, I'll replicate it for the single node AWS deployment this morning.

2020-07-11 03:56 UTC, mandoonandy approved these changes

2020-07-11 03:56 UTC, merged