Feature remove submodules and use spinouts
shakenfist/deploy pull request #58
Opened 2020-08-14 22:51 UTC by mikalstill

2020-08-15 08:03 UTC, mandoonandy requested changes

2020-08-15 08:03 UTC, mandoonandy commented on README.md
> +cd deploy/ansible
Is this step required for ansible-galaxy installation?

2020-08-15 08:03 UTC, mandoonandy commented on README.md
> +export VARIABLES="ADMIN_PASSWORD=p4ssw0rd FLOATING_IP_BLOCK=192.168.20.0/24"
Setting ADMIN_PASSWORD in $VARIABLES leads to duplication relying on Ansibles's case-insensitvity and precedence. 
I'm thinking these two values should be set as individual environment variables.

2020-08-15 08:09 UTC, mikalstill commented on README.md
> +cd deploy/ansible
No, it turns out it isn't. I'll remove it.

2020-08-15 08:09 UTC, mikalstill commented on README.md
> +export VARIABLES="ADMIN_PASSWORD=p4ssw0rd FLOATING_IP_BLOCK=192.168.20.0/24"
So something more like:

```
export ADMIN_PASSWORD=p4ssw0rd
export FLOATING_IP_BLOCK="192.168.20.0/24"
```

?

2020-08-15 08:41 UTC, mandoonandy commented on README.md
> +export VARIABLES="ADMIN_PASSWORD=p4ssw0rd FLOATING_IP_BLOCK=192.168.20.0/24"
yep. that was my intention.

2020-08-15 23:18 UTC, mikalstill commented on README.md
> +cd deploy/ansible
Done.

2020-08-15 23:18 UTC, mikalstill commented on README.md
> +export VARIABLES="ADMIN_PASSWORD=p4ssw0rd FLOATING_IP_BLOCK=192.168.20.0/24"
Done.

2020-08-16 00:48 UTC, mandoonandy approved these changes
LGTM

2020-08-16 00:48 UTC, merged